openapi: 3.0.0
info:
  title: reqres
  description: A free testing API
  version: "3.0"

servers:
  - url: https://reqres.in/
    description: Test create user

paths:
  /api/users:
    get:
      operationId: list_users
      description: Lists users
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false

      responses:
        "200":
          description: Response

    post:
      operationId: create_user
      description: Creates a user

      requestBody:
        description: Optional description
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                job:
                  type: string
              required:
                - name
                - job
      responses:
        "201": # status code
          description: A JSON response containing attributes of the created user
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: name
                  job:
                    type: string
                    description: job
                  id:
                    type: string
                    description: Id
                  createdAt:
                    type: string
                    description: created at date
