openapi: 3.0.0
info:
  title: MS Graph
  description: Microsoft Graph API
  version: "1.0"

servers:
  - url: https://graph.microsoft.com/v1.0
    description: MS Graph API v1.0

paths:
  /me:
    get:
      operationId: get_my_profile
      summary: N/A
      description: N/A

      responses:
        "200":
          description: Response

security:
  - oAuth2ClientCredentials: []

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: See Microsoft Graph API
      flows:
        clientCredentials:
          # tokenUrl: https://login.microsoftonline.com/6e43eaf9-dd69-4896-bcf9-9228f64d21b2/oauth2/v2.0/token
          tokenUrl: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
          scopes: {} # do not use scopes
